### ISSUE TITLE
ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type numpy.ndarray).

### ISSUE THREAD

**Issue by Vaishnavi-ambati** [HOD101s/RockPaperScissor-AI-#1]
![image](https://user-images.githubusercontent.com/50202237/89318799-e9901e80-d69c-11ea-91ac-bd55b1f37ff7.png)

Getting this error while executing. Please give your inputs.

**Comment by HOD101s** [comment]
Hi,

If you don't mind please share the jupyter notebook and a sample of the
data you're using for training. I can then help you better.

Regards

**Comment by Vaishnavi-ambati** [comment]
Hi,

Thanks for replying. Here are the links for the dataset and modeling file.
1) Dataset - https://drive.google.com/drive/folders/1_SXVaBJIAHmcuKrZILKpQqr2AuKmJmuH?usp=sharing
2) Modeling - https://colab.research.google.com/drive/19MVulE1s-ysGYqpMAP8xEVaktUyuQM4E?usp=sharing
(I have used the same file in your GitHub repo without changing anything) 

Thank you,
Vaishnavi Ambati

**Comment by Benson1198** [comment]
Hi, 

I'm having the same issue
ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type numpy.ndarray).

**Comment by HOD101s** [comment]
`imgData = np.array(imgData)
labels = np.array(labels)`

try using np.asarray() instead

This link might be helpful
https://stackoverflow.com/questions/58636087/tensorflow-valueerror-failed-to-convert-a-numpy-array-to-a-tensor-unsupporte

**Comment by Vaishnavi-ambati** [comment]
Tried np.asarray() also but still getting the same error.

**Comment by Nitin-Rana** [comment]
> Tried np.asarray() also but still getting the same error.
Here, problem is with your imgdata dimensions. Rectify it, will work for sure.

**Comment by HOD101s** [comment]
Closing issue due to no more updates
