### ISSUE TITLE
Could not broadcast input array from shape

### ISSUE THREAD

**Issue by GrayDelta** [HOD101s/RockPaperScissor-AI-#3]
Hi, I try to test, but when i try to train model, it show me error

imgData = np.array(imgData)
ValueError: could not broadcast input array from shape (300,300,3) into shape (300)

I try to fix it but without result, can you help?

**Comment by HOD101s** [comment]
So your images are not being processed properly. Try using the getData script to collect your data.

**Comment by sunying1304** [comment]
Hi, I collected the data by getData script, yet met the same problem. Could you help?

**Comment by sunying1304** [comment]
Later I've found the issue, line 26 in getData.py is sized as (300,350), should change [100,450] to [150,450]
