### ISSUE TITLE
Getting an error in Getdata.py file

### ISSUE THREAD

**Issue by deepikagoel1** [HOD101s/RockPaperScissor-AI-#5]
Traceback (most recent call last):
  File "getData.py", line 18, in <module>
    ct = int(sys.argv[2])
ValueError: invalid literal for int() with base 10: 'startIndex'
[ WARN:0] global C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-fgndhvyk\opencv\modules\videoio\src\cap_msmf.cpp (438) `anonymous-namespace'::SourceReaderCB::~SourceReaderCB termin
ating async callback

**Comment by HOD101s** [comment]
could you send the command you are using. It looks like you are not sending all required params. please read docs.

**Comment by HOD101s** [comment]
Closing issue due to no updates
